Version 1.0.0
9.0 > 10.0

added markdown preview using showdown js library

update

Add Ukrainian translation to mik_dms and muk_dms_access

Documents 2.0

publish muk_dms - 11.0

v12

[IMP] : black, isort, prettier

[MIG] dms: from muk_dms to dms

[MIG] Dms tag

[MIG] dms: File

[MIG][13.0] dms: Finish migration

[IMP] Minor mig fixes

[MIG] dms: fix tests

[IMP] Add security groups

[ADD] dms: add funcionality of muk_dms_file

[MIG] dms: File functionality

[IMP] dms: Allow to drag and drop

[FIX] Various fixes

[IMP] dms: Add mail

[FIX] dms: remove unused code and fixing: webpanel, migration, thumbnails, preview

[IMP] dms: add migration script for muk_dms

[13.0][MIG] dms: make migrations scripts compatible with older
versions of muk_dms than 12.0.2.0.0.

Tested from 1.2.4 version.

[FIX] dms: Download file with its proper name

[FIX] dms: missing banner images & Load fields on the usual way

[FIX] dms: Fix preview widget

[FIX] dms: fix wrong test

In v13, this test is programmed in such a way that the demo user is supposed to be able to copy that subdirectory: https://github.com/OCA/dms/blob/c3f802db43362127e70d8c7b4987fb71d4c1f01c/dms/tests/test_directory.py#L40

However, in https://github.com/OCA/dms/pull/7 that test was modified indicating that demo user didn't have permissions to do that: https://github.com/OCA/dms/blob/e3b6d8d24534f2a68bfb88e310cc70cefe46bb64/dms/tests/test_directory.py#L39

Rolling back that change to ensure premissions remain the same in both versions of the module.

Also changing the directory to test to ensure it contains no SVG files, whose detection seems to differ among environments, and which have some specific permission restrictions that can make the modified test fail or pass.

@Tecnativa TT25645

[IMP] dms: Portal

[FIX] dms: /my/dms change to user and separate some urls in some functions

[FIX] : Fix mimetype error in some files (.xlsx for example)

[ADD] DMS integration with attachment

[IMP] dms: Attachment integration

[IMP] dms: Attachment integration

Added translation using Weblate (Hebrew)

Translated using Weblate (Hebrew)

Currently translated at 80.4% (254 of 316 strings)

Translation: dms-13.0/dms-13.0-dms
Translate-URL: https://translation.odoo-community.org/projects/dms-13-0/dms-13-0-dms/he_IL/

Added translation using Weblate (Dutch)

[FIX] dms: Remove request website user try

[FIX] dms: Fix error when web_drop_target addon used to create new file + remove content field in tree

[FIX] dms: Adapt to 13.0

Added translation using Weblate (Italian)

[IMP] dms: Integrate with mail_preview_base

[FIX] dms: Kanban view

[FIX] dms: Remove category creation in kanban tag view to prevent error

[FIX] dms: Use sudo() in attachment operacion (search dms directories and auto-create directories and files if is needed) to prevent error in attachment(s) creation

Co-authored-by: Jairo Llopis <jairo.llopis@tecnativa.com>

[REF+FIX] dms: Refactor code to create abstract.dms.mixin to contain fields or functions that is used in some models (in these case some fields appear in directory and field and some functions about it).
Fixed problem happen when access to file or folder view if record ref is set (file or folder has been created in attachment creation in partner for example)

[FIX] dms: Prevent error when archive records and later process try to create again + Add test to check it

[FIX] dms: Add domain operator

Fixes issue #69

[12.0] [FIX] dms: Check `default_directory_id` context key

When creating an attachment, check `default_directory_id` too because this key comes from kanban js view and it's like `active_id` when creating files from drag and drop (drop target).

This change will allow to view the new file on the associated record if the folder has `res_model` and `res_id` (the parent folder is an attachment storage)

Fixes #72

[FIX] dms: Prevent parent_id error in directories in some UI cases [FIX] dms: Change allowed_model_ids field in directory to related [FIX] dms: Change res_model + res_id fields in files to related

[IMP] dms: Inherit permissions from related records

[IMP] dms: black, isort, prettier

[MIG] dms: Migration to 14.0

[FIX] dms: Remove action column in portal (only used in files) and convert file name to link (download)

[FIX] dms: Fix error in portal with access_token

[FIX] dms: Improve tests to prevent error if installed other addons after dms install and new addons auto-create partners

[FIX] dms: Apply _apply_access_groups correctly (specially according to files) to get only records to get only allowed records according to directories groups.

[FIX] improve some queries

... so to speak.

@Tecnativa TT29847

[FIX] dms: cascade removal of related files/directories

When some dms.directory or dms.file was related to a real DB record (a.k.a. attachment storage), if the record got deleted, the DMS mirror was still alive.

If the dms.storage had inherit_access_from_parent_record=True, the situation got worse because the dms.directory became visible to everyone.

@Tecnativa TT30223

[FIX] dms: do not fail for missing models on upgrade

Module upgrade is done in a constrained environment where the `dms` module is only aware of models declared in its dependency tree.

If some upgrade operation tries to write to a file or directory that is attached to a model-based storage, the upgrade would fail with a `KeyError` when trying to get the model.

This fix allows normal and predictable upgrades in such cases.

@Tecnativa TT29847

[FIX] dms: image thumbnails performance

- Portal was too slow to load because every thumbnail came base64-encoded. Instead, now it loads resources externally, making the initial request much faster, and benefiting from caching.
- Fields `custom_thumbnail_medium` and `custom_thumbnail_small` are now stored, because non-stored thumbnails become performance bottlenecks easily.
- Added field `icon_url` that allows using always the exact same image path for the exact same mime type. This saves a lot of requests and bandwidth.
- Fields `thumbnail`, `thumbnail_medium` and `thumbnail_small` are now only used in forms, and do not perform resize operations.
- Remove unused `size` parameter in thumbnail internal getters.
- All thumbnail fields were getting resized to sizes that were different from the sizes that, later, were actually used in UI, thus making the UI always re-resize them. Removed that nonsense. Thumbnails now use the same size that the UI will require, and then UI needs to ask for no resizes.
- Typo fixed in unknown file default thumbnail.
- Do your customers really know what a mime type is? I bet not. Remove "type" column from portal. Thumbnails provide all the required information.

@Tecnativa TT29847

[FIX] dms: Fix multi-company rules + migration scripts

[REF] dms: modify permissions computation

- Remove `perm_read` field from `dms.access.group`. It is redundant to the mere existence of the group. Otherwise, users could be able to create, write or unlink records that they cannot read. To avoid confusion, it is removed.
- Add portal group access to mails directory, to make one test pass. This was a false positive before.
- Forbid `dms.access.group` recursiveness.
- Compute inclusive permissions in `dms.access.group`, which combine current group with parent group permissions.
- Rely on domain search of `permission_{create,read,unlink,write}` in `dms.directory` and `dms.file` when checking those accesses to records. These search methods are improved to reflect permission reality and add it to the domain.
- Added a hack to workaround situations where the current context user is superuser, but it's actually checking for other user permissions.
- These checks are added as normal `ir.rule` records.
- To create something in a directory, you need create access in the parent directory.
- For other operations, and only in subdirs, the own dir access is checked.
- Batch operations when checking inherited permissions.
- Remove many custom methods to check access, now that we use ORM's.
- Fix custom cascade dir unlink.
- Use `consteq()` when checking access tokens, for security.
- Remove duplicated security computations from `dms.directory` and `dms.file`. Use proper inheritance.
- Use `ir.rule` for checking locked files.
- Add or fix tests for new permissions model.
- Define groups to root folder "Media" (according to the previous expected operation).
- Add the Admin + Demo user group to "Mails" folder (according to the previous expected operation).
- Add sudo() in the creation of the directory to "force" that it can be created because the correct parameter of permission_read can only be correctly defined when the record exists and the complete_group_ids records have been created (in 13.0 it is not necessary).
- Add default group (Admin + Demo user) when creating directive in tests.
- Corrections tests of record_ref
- Fix prevent error related to mail_message parent not exists in some cases (directory)

@Tecnativa TT29847

Co-authored-by: Víctor Martínez <victor.martinez@tecnativa.com>

[FIX] dms: respect computed security rules in all contexts

The fix is similar to [v12 creation workaround][1], with some differences:

1. It is applied to both `dms.directory` and `dms.file`, as both need to use this.
2. In v13 Odoo uses now `_filter_access_rules_python()` by default, which is incompatible with DMS' security hack, so we make use of `_filter_access_rules()` always. Some comments explain the HACK.
3. `flush()` before doing the creation access check, so all data is in DB before we issue the `SELECT` needed to check permissions properly.

[1]: https://github.com/OCA/dms/blob/db9cb933ba4f29cc1a610190c32e2ff4bb16b1ce/dms/models/directory.py#L654-L661

[FIX] dms: Prevent error (apply sudo()) when recursive directories read from files creation in _compute_path() if some directory not allowed from user

[FIX] dms: Fix tests for environments that add other groups to base users

Instead of relying on base users, create the ones we need for the test.

[REF] dms: Adapt to 14.0

[IMP] dms: automatic image thumbnails

- If a dms.file contains an image, use it as thumbnail automatically, and hide controls for customizing that record's thumbnail.
- Remove `.png` icons, unused.
- Clarify distinction between icon and thumbnail.
- Inherit from `image.mixin` for thumbnails.
- Save custom thumbnails as attachments instead of db binary fields.

@Tecnativa TT31004

Explicit Access Group instructions

[FIX] dms: Add python-magic library to readme

[FIX] dms: Drag & Drop

[IMP] dms: Set the drop target to the kanban view, excluding the search panel

[FIX] dms: Pending attribute mimetype

[FIX] dms: Show the total of files (of all subdirectories) in the form view of the directories.

[FIX] dms: Define the file extension correctly (even if there is no extension in the file name).

[FIX] dms: Prevent CacheMis error from count_total_files in some NewId use cases.
TT34095

[FIX] dms: Change size field type from integer to float to prevent 2147483647 limit from postgresql.

TT33935

[FIX] dms: Replace the content field with size in the form view of the directory (file_ids field) because it is totally wrong to try to show that field.
TT34353

[FIX] dms: The internal user group is added as an inheritance to the new group.

[MIG] dms: Migration to 15.0

[MIG] dms: Finish migration

[UPD] Update dms.pot

[UPD] README.rst

[FIX] dms: Add Archived ribbon in form views and remove active field from tree views.

[UPD] Update dms.pot

dms 15.0.1.1.0

Update translation files

Updated by "Update PO files to match POT (msgmerge)" hook in Weblate.

Translation: dms-15.0/dms-15.0-dms
Translate-URL: https://translation.odoo-community.org/projects/dms-15-0/dms-15-0-dms/

[FIX] dms: do_warn method no longer available in v15

Translated using Weblate (German)

Currently translated at 98.2% (333 of 339 strings)

Translation: dms-15.0/dms-15.0-dms
Translate-URL: https://translation.odoo-community.org/projects/dms-15-0/dms-15-0-dms/de/

dms 15.0.1.1.1

[IMP+FIX] dms: Searchpanel changes:

- Set limit=0 to prevent js default limit https://github.com/odoo/odoo/blob/15.0/addons/web/static/src/search/search_arch_parser.js#L10
- Removes the context of fields (not used in .js calls).
- Display the short name of the category (no hierarchy) in Directory menu.

dms 15.0.1.2.0

[IMP] dms: Use _prepare_home_portal_values() function.

[IMP] dms: Refactor tests.

dms 15.0.1.2.1

dms 15.0.1.3.0

[IMP] dms: Changes in file tree view: - Set multi_edit - Add tag_ids field - Remove path_names field - Remove FieldPathNames (related to path_names)

[FIX] dms: Compute mimetype in dms_file correctly to allow preview

[IMP] dms: automatic image thumbnails

[IMP] dms: Show in directory kaban view only root directories (Change All text to Root) + Change to searchpanel directory_id (in files) or parent_id (in directories) to filter equal and not child_of

[FIX] dms: Show directory short name in searchpanel.

[UPD] Update dms.pot

dms 15.0.1.4.0

Update translation files

Updated by "Update PO files to match POT (msgmerge)" hook in Weblate.

Translation: dms-15.0/dms-15.0-dms
Translate-URL: https://translation.odoo-community.org/projects/dms-15-0/dms-15-0-dms/

[FIX] dms: Searchpanel from directories

We need to overwrite function from directories because odoo only return
records with childs (very weird for user perspective).
All records are returned now.

[FIX] dms: Add operator parameter required (forgotten at https://github.com/OCA/dms/pull/122/commits/907d8f37a0515313c935606e78b16b32af60c3ee)

dms 15.0.1.5.0

[FIX] dms: skip attachment creation when storage type is different from attachment

dms 15.0.1.5.1

[FIX] dms: Remove migrations folder from 14.0

[FIX] dms: Remove parent_id defined if you do not have access to it (search panel directory).

TT41585

[FIX] dms: Limit breadcrumb from portal to directories you have access to.

TT41585

[FIX] dms: Get the "parent" directories (those of the top level to which you have access) in the portal view.

TT41585

dms 15.0.1.5.2

[FIX] dms: Use the correct domain with inherit_access_from_parent_record field

dms 15.0.1.6.0

[IMP] dms: Add action_dms_file_wizard_selector action.

TT41512

[UPD] Update dms.pot

[UPD] README.rst

dms 15.0.1.7.0

Update translation files

Updated by "Update PO files to match POT (msgmerge)" hook in Weblate.

Translation: dms-15.0/dms-15.0-dms
Translate-URL: https://translation.odoo-community.org/projects/dms-15-0/dms-15-0-dms/

[FIX] dms: dms.file thumbnail generation checks for supported mimetypes

The method _compute_image_1920 of dms_file checks if the file is of
mimetype image and tries to use it as a thumbnail.
However, there are several types of image files that Odoo/PIL
cannot work with, leading to the following error:

```
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/tools/image.py", line 404, in base64_to_image
    return Image.open(io.BytesIO(base64.b64decode(base64_source)))
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 2687, in open
    % (filename if filename else fp))
OSError: cannot identify image file <_io.BytesIO object at 0x7f0a6ecb1780>
```

and also further down

```
odoo.exceptions.UserError: ('This file could not be decoded as an image file. Please try with a different file.', '')
```

Examples of such files are CAD files (mimetype: image/vnd.dwg)
For a list of all mimetypes starting with "image/" see:
https://www.iana.org/assignments/media-types/media-types.xhtml#image

dms 15.0.1.7.1

[IMP] dms: more restrictive access rights for access groups

Change in the permissions for DMS Access Groups:

- Not every user can create new access groups, but only dms_users.
- DMS managers (not admin users) can manage every access group
- Add tests

After this change:

- the base user has read only access
- the group_dms_user can create, and can write and unlink their own groups
- the group_dms_manager can do everything on every group.

dms 15.0.1.8.0

[IMP] dms: Increase the speed of tests

dms 15.0.1.8.1

[FIX] dms: Explicitly exclude the pdf type in the image_1920 field of the files.

TT43563